services:
  limitr:
    build: # Don't change anything in this section unless you know what you're doing
      context: .
      dockerfile: Dockerfile
    networks:
      - containerNetwork
    ports:
      - "127.0.0.1:7654:7654" # Change the left side to the port you want to expose the service on
    volumes:
      - ./ssl:/ssl # Replace ONLY the left side with the path to your SSL certificates
    restart: unless-stopped
    environment: # HERE you can define the environment variables, details available in the README
      - FORWARD_URL=https://www.beehive.net # The URL to forward the requests to
      - RATE_LIMIT=50 # Requests allowed per time window
      - TIME_WINDOW=120 # Time window in seconds
      - IP_HEADER_KEY=X-Forwarded-For # The header key that contains the IP address. Comment out if IP should be read from connection normally
      - REDIS_ADDR=redis:6379 # Don't change this unless you know what you're doing
      - REDIS_PASSWORD=ChangeMe! # The password for the Redis server. Set a new one here and in redisconfig/redis.conf if using in production
      - VERBOSE_MODE=true # Set this to true if you want to see the logs in the console
      # - USE_TLS=true # Uncomment this line if you want to use TLS and have SSL certificates (both .key and .pem files). Make sure to set the correct path to the containing folder in the 'volumes' section above
    depends_on: # Don't change anything in this section unless you know what you're doing
      - redis
  redis: # Don't change anything in this section unless you know what you're doing
    image: redis:latest
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - containerNetwork
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
networks:
  containerNetwork:
    driver: bridge